export const musicApp = {
    name: 'Music Player',
    content: `
        <div class="music-container">
            <div class="music-header">
                <h2>NEURAL_STIMULATION_PROTOCOL</h2>
                <p>Select audio frequency for enhanced productivity:</p>
            </div>
            
            <div class="music-controls">
                <button onclick="window.musicPlayer.playSynth()">SYNTHWAVE</button>
                <button onclick="window.musicPlayer.playCyber()">CYBERPUNK</button>
                <button onclick="window.musicPlayer.stop()">STOP</button>
            </div>
            
            <!-- Music Visualizer -->
            <div class="visualizer-container">
                <div class="visualizer-title">AUDIO_WAVEFORM</div>
                <div class="visualizer-bars" id="visualizer-bars">
                    <!-- Bars will be generated by JavaScript -->
                </div>
                <div class="visualizer-status" id="visualizer-status">STATUS: IDLE</div>
            </div>
            
            <div class="music-info">
                <p>Current Track: <span id="current-track">READY</span></p>
                <p>> AUDIO SYSTEMS: <span id="audio-status">ONLINE</span></p>
                <p>> IMMERSION: <span id="immersion-level">87%</span></p>
            </div>
        </div>
    `,
    width: 500,
    height: 500
};